# Generated by Django 2.1.7 on 2019-04-08 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qustion',
            new_name='Question',
        ),
    ]
